#!/usr/bin/env bash
set -Eeuo pipefail

install_kamailio() {
  install_kamailio_repository
  MNSCLOUD_KAMAILIO_PACKAGE_PROFILE=webrtc mrtk_ensure_kamailio
}

render_kamailio_config() {
  install -d -m 0755 "$KAMAILIO_MNS_DIR"
  install -m 0644 "$REPO_DIR/config/kamailio/kamailio.cfg.template" /etc/kamailio/kamailio.cfg
  install -m 0644 "$REPO_DIR/config/kamailio/"*.template "$KAMAILIO_MNS_DIR/"
  for file in "$KAMAILIO_MNS_DIR/"*.template; do
    mv "$file" "${file%.template}"
  done
  render_kamailio_rtpengine_socket
  render_kamailio_listeners
  render_kamailio_sip_targets
}

validate_kamailio() {
  run kamailio -c -f /etc/kamailio/kamailio.cfg
}

render_kamailio_listeners() {
  local config_file="$CONFIG_DIR/config.json"
  local output_tmp
  local output_file="$KAMAILIO_MNS_DIR/mnscloud-listen.cfg"
  local private_ip
  output_tmp="$(mktemp)"

  private_ip=""
  if [[ -s "$config_file" ]]; then
    private_ip="$(jq -r '(.server.privateIP // .data.server.privateIP // "")' "$config_file" 2>/dev/null |
      tr ',' '\n' |
      sed 's/^[[:space:]]*//;s/[[:space:]]*$//' |
      awk '/^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$/ { print; exit }')"
  fi
  if [[ -z "$private_ip" ]]; then
    private_ip="$(detect_kamailio_private_ipv4 || true)"
  fi

  {
    printf '# This file is generated by MNSCloud. Do not edit manually.\n'
    printf '# Source: %s\n\n' "$config_file"
    printf 'listen=tcp:127.0.0.1:5066\n'
    printf 'listen=udp:127.0.0.1:5060\n'

    if [[ -n "$private_ip" ]] && ip -o -4 addr show | awk '{ print $4 }' | cut -d/ -f1 | grep -qx "$private_ip"; then
      printf 'listen=udp:%s:5060\n' "$private_ip"
      printf 'listen=tcp:%s:5060\n' "$private_ip"
    elif [[ -n "$private_ip" ]]; then
      warn "Skipping private Kamailio SIP listener because $private_ip is not assigned to this host."
    else
      warn "No private IPv4 found in WebRTC runtime config. SIP target routing may fail for non-loopback destinations."
    fi
  } > "$output_tmp"

  install -m 0644 "$output_tmp" "$output_file"
  rm -f "$output_tmp"
}

detect_kamailio_private_ipv4() {
  local detected_ip
  detected_ip="$(ip -o -4 route get 1.1.1.1 2>/dev/null | awk '
    {
      for (i = 1; i <= NF; i++) {
        if ($i == "src") {
          print $(i + 1)
          exit
        }
      }
    }')"
  [[ -n "$detected_ip" ]] || return 0
  printf '%s\n' "$detected_ip"
}

render_kamailio_rtpengine_socket() {
  local config_file="$CONFIG_DIR/config.json"
  local output_file="$KAMAILIO_MNS_DIR/mnscloud-rtpengine.cfg"
  local socket

  socket="udp:127.0.0.1:2223"
  if [[ -s "$config_file" ]]; then
    socket="$(jq -r '(
        .server.rtpengineSocket
        // .server.mediaSocket
        // .data.server.rtpengineSocket
        // .data.server.mediaSocket
        // .media.rtpengineSocket
        // .data.media.rtpengineSocket
        // ""
      )' "$config_file" 2>/dev/null | tr -d '\r\n')"
    socket="${socket:-udp:127.0.0.1:2223}"
  fi

  if [[ ! "$socket" =~ ^(udp|tcp):[A-Za-z0-9._:-]+:[0-9]{1,5}$ ]]; then
    warn "Invalid rtpengine socket from runtime config; using udp:127.0.0.1:2223."
    socket="udp:127.0.0.1:2223"
  fi

  sed "s#{{RTPENGINE_SOCKET}}#${socket}#g" "$output_file" > "${output_file}.tmp"
  install -m 0644 "${output_file}.tmp" "$output_file"
  rm -f "${output_file}.tmp"
  ok "Kamailio rtpengine socket: ${socket}"
}

render_kamailio_sip_targets() {
  local config_file="$CONFIG_DIR/config.json"
  local output_tmp
  local output_file="$KAMAILIO_MNS_DIR/mnscloud-sip-targets.cfg"
  output_tmp="$(mktemp)"

  {
    printf '# This file is generated by MNSCloud. Do not edit manually.\n'
    printf '# Source: %s\n\n' "$config_file"
    printf 'route[MNSCLOUD_ROUTE] {\n'
    printf '    xlog("L_INFO", "MNSCloud WebRTC route request method=$rm ruri=$ru from=$fu source=$si\\\\n");\n\n'

    if [[ -s "$config_file" ]]; then
      jq -r '(.sipTargets // .data.sipTargets // []) | .[] | @base64' "$config_file" | while IFS= read -r encoded; do
        local domain sip_domain host port transport target_type target_host target_uri route_condition
        domain="$(printf '%s' "$encoded" | base64 -d | jq -r '.domain // empty' | tr '[:upper:]' '[:lower:]')"
        sip_domain="$(printf '%s' "$encoded" | base64 -d | jq -r '.sipDomain // empty' | tr '[:upper:]' '[:lower:]')"
        host="$(printf '%s' "$encoded" | base64 -d | jq -r '.host // empty')"
        port="$(printf '%s' "$encoded" | base64 -d | jq -r '.port // 5060')"
        transport="$(printf '%s' "$encoded" | base64 -d | jq -r '.transport // "udp"' | tr '[:upper:]' '[:lower:]')"
        target_type="$(printf '%s' "$encoded" | base64 -d | jq -r '.targetType // empty' | tr '[:upper:]' '[:lower:]')"

        if [[ ! "$domain" =~ ^[a-z0-9][a-z0-9.-]*[a-z0-9]$ ]]; then
          warn "Skipping invalid WebRTC SIP target domain from runtime config: $domain"
          continue
        fi
        if [[ -n "$sip_domain" && ! "$sip_domain" =~ ^[a-z0-9][a-z0-9.-]*[a-z0-9]$ ]]; then
          warn "Ignoring invalid WebRTC SIP target SIP domain from runtime config: $sip_domain"
          sip_domain=""
        fi
        if [[ ! "$host" =~ ^[A-Za-z0-9._:-]+$ ]]; then
          warn "Skipping invalid WebRTC SIP target host for $domain"
          continue
        fi
        if [[ "$host" == "127.0.0.1" || "$host" == "::1" || "$host" == "localhost" ]]; then
          warn "Skipping local-loop WebRTC SIP target host for $domain"
          continue
        fi
        if [[ ! "$target_type" =~ ^(pabx|softswitch)$ ]]; then
          warn "Skipping invalid WebRTC SIP target type for $domain"
          continue
        fi
        if [[ ! "$port" =~ ^[0-9]+$ || "$port" -lt 1 || "$port" -gt 65535 ]]; then
          warn "Skipping invalid WebRTC SIP target port for $domain"
          continue
        fi
        if [[ ! "$transport" =~ ^(udp|tcp|tls)$ ]]; then
          warn "Skipping invalid WebRTC SIP target transport for $domain"
          continue
        fi

        target_host="$host"
        if [[ "$target_host" == *:* && "$target_host" != \[*\] ]]; then
          target_host="[$target_host]"
        fi
        target_uri="sip:${target_host}:${port};transport=${transport}"
        route_condition="\$rd == \"${domain}\""
        if [[ -n "$sip_domain" && "$sip_domain" != "$domain" ]]; then
          route_condition="${route_condition} || \$rd == \"${sip_domain}\""
        fi

        printf '    if (%s) {\n' "$route_condition"
        printf '        $du = "%s";\n' "$target_uri"
        printf '        xlog("L_INFO", "MNSCloud WebRTC routing domain=$rd web_domain=%s sip_domain=%s type=%s target=%s\\\\n");\n' "$domain" "${sip_domain:-$domain}" "$target_type" "$target_uri"
        printf '        if (!is_method("REGISTER")) {\n'
        printf '            record_route();\n'
        printf '        }\n'
        printf '        if (!t_relay()) {\n'
        printf '            sl_reply_error();\n'
        printf '        }\n'
        printf '        exit;\n'
        printf '    }\n\n'
      done
    fi

    printf '    sl_send_reply("404", "No realtime SIP target");\n'
    printf '    exit;\n'
    printf '}\n'
  } > "$output_tmp"

  install -m 0644 "$output_tmp" "$output_file"
  rm -f "$KAMAILIO_MNS_DIR/mnscloud-pabx-routes.cfg"
  rm -f "$output_tmp"
}
