#!/usr/bin/env bash
set -Eeuo pipefail

install_kamailio() {
  install_kamailio_repository
  apt_install \
    kamailio kamailio-websocket-modules kamailio-tls-modules \
    kamailio-json-modules kamailio-utils-modules kamailio-extra-modules \
    kamailio-outbound-modules kamailio-presence-modules
}

render_kamailio_config() {
  install -d -m 0755 "$KAMAILIO_MNS_DIR"
  install -m 0644 "$REPO_DIR/config/kamailio/kamailio.cfg.template" /etc/kamailio/kamailio.cfg
  install -m 0644 "$REPO_DIR/config/kamailio/"*.template "$KAMAILIO_MNS_DIR/"
  for file in "$KAMAILIO_MNS_DIR/"*.template; do
    mv "$file" "${file%.template}"
  done
  render_kamailio_listeners
  render_kamailio_pabx_routes
}

validate_kamailio() {
  run kamailio -c -f /etc/kamailio/kamailio.cfg
}

render_kamailio_listeners() {
  local config_file="$CONFIG_DIR/config.json"
  local output_tmp
  local output_file="$KAMAILIO_MNS_DIR/mnscloud-listen.cfg"
  local private_ip
  output_tmp="$(mktemp)"

  private_ip=""
  if [[ -s "$config_file" ]]; then
    private_ip="$(jq -r '(.server.privateIP // .data.server.privateIP // "")' "$config_file" 2>/dev/null |
      tr ',' '\n' |
      sed 's/^[[:space:]]*//;s/[[:space:]]*$//' |
      awk '/^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$/ { print; exit }')"
  fi

  {
    printf '# This file is generated by MNSCloud. Do not edit manually.\n'
    printf '# Source: %s\n\n' "$config_file"
    printf 'listen=tcp:127.0.0.1:5066\n'
    printf 'listen=udp:127.0.0.1:5060\n'

    if [[ -n "$private_ip" ]] && ip -o -4 addr show | awk '{ print $4 }' | cut -d/ -f1 | grep -qx "$private_ip"; then
      printf 'listen=udp:%s:5060\n' "$private_ip"
      printf 'listen=tcp:%s:5060\n' "$private_ip"
    elif [[ -n "$private_ip" ]]; then
      warn "Skipping private Kamailio SIP listener because $private_ip is not assigned to this host."
    else
      warn "No private IPv4 found in WebRTC runtime config. PABX routing may fail for non-loopback SIP targets."
    fi
  } > "$output_tmp"

  install -m 0644 "$output_tmp" "$output_file"
  rm -f "$output_tmp"
}

render_kamailio_pabx_routes() {
  local config_file="$CONFIG_DIR/config.json"
  local output_tmp
  local output_file="$KAMAILIO_MNS_DIR/mnscloud-pabx-routes.cfg"
  output_tmp="$(mktemp)"

  {
    printf '# This file is generated by MNSCloud. Do not edit manually.\n'
    printf '# Source: %s\n\n' "$config_file"
    printf 'route[MNSCLOUD_ROUTE] {\n'
    printf '    xlog("L_INFO", "MNSCloud WebRTC route request method=$rm ruri=$ru from=$fu source=$si\\\\n");\n\n'

    if [[ -s "$config_file" ]]; then
      jq -r '(.pabxTargets // .data.pabxTargets // []) | .[] | @base64' "$config_file" | while IFS= read -r encoded; do
        local domain host port transport target_host target_uri
        domain="$(printf '%s' "$encoded" | base64 -d | jq -r '.domain // empty' | tr '[:upper:]' '[:lower:]')"
        host="$(printf '%s' "$encoded" | base64 -d | jq -r '.host // empty')"
        port="$(printf '%s' "$encoded" | base64 -d | jq -r '.port // 5060')"
        transport="$(printf '%s' "$encoded" | base64 -d | jq -r '.transport // "udp"' | tr '[:upper:]' '[:lower:]')"

        if [[ ! "$domain" =~ ^[a-z0-9][a-z0-9.-]*[a-z0-9]$ ]]; then
          warn "Skipping invalid PABX route domain from runtime config: $domain"
          continue
        fi
        if [[ ! "$host" =~ ^[A-Za-z0-9._:-]+$ ]]; then
          warn "Skipping invalid PABX route host for $domain"
          continue
        fi
        if [[ "$host" == "127.0.0.1" || "$host" == "::1" || "$host" == "localhost" ]]; then
          warn "Skipping local-loop PABX route host for $domain"
          continue
        fi
        if [[ ! "$port" =~ ^[0-9]+$ || "$port" -lt 1 || "$port" -gt 65535 ]]; then
          warn "Skipping invalid PABX route port for $domain"
          continue
        fi
        if [[ ! "$transport" =~ ^(udp|tcp|tls)$ ]]; then
          warn "Skipping invalid PABX route transport for $domain"
          continue
        fi

        target_host="$host"
        if [[ "$target_host" == *:* && "$target_host" != \[*\] ]]; then
          target_host="[$target_host]"
        fi
        target_uri="sip:${target_host}:${port};transport=${transport}"

        printf '    if ($rd == "%s") {\n' "$domain"
        printf '        $du = "%s";\n' "$target_uri"
        printf '        xlog("L_INFO", "MNSCloud WebRTC routing domain=%s target=%s\\\\n");\n' "$domain" "$target_uri"
        printf '        if (!is_method("REGISTER")) {\n'
        printf '            record_route();\n'
        printf '        }\n'
        printf '        if (!t_relay()) {\n'
        printf '            sl_reply_error();\n'
        printf '        }\n'
        printf '        exit;\n'
        printf '    }\n\n'
      done
    fi

    printf '    sl_send_reply("404", "No PABX target");\n'
    printf '    exit;\n'
    printf '}\n'
  } > "$output_tmp"

  install -m 0644 "$output_tmp" "$output_file"
  rm -f "$output_tmp"
}
